const questions=[
    {
            id:"1" , 
            question:"What does HTML stand for?",
            opt1:"Hyper Trainer Marking Language ",
            opt2:"Hyper Text Markup Language",
            opt3:"Hyper Text Markdown Language",
            opt4:"High Text Markup Language",
            ans:"Hyper Text Markup Language",
        
    },
    {       id:"2" , 
            question: "Which tag is used to define an image in HTML?",
            opt1:"<img>",
            opt2:"<image>",
            opt3:"<src>",
            opt4:"<picture>.",
            ans:"<img>",
    },
    {
            id:"3" , 
            question: "Which HTML attribute specifies an inline style",
            opt1:"style",
            opt2:"src",
            opt3:"title",
            opt4:"longdesc",
            ans:"style",
    },
    {
            id:"4" ,
            question:"Which property is used to change the text color of an element",
            opt1:"font-color",
            opt2:"text-color",
            opt3:"color",
            opt4:"background-color",
            ans:"color",
    
    },
    {
            id:"5" ,
            question:"How do you make each word in a text start with a capital letter",
            opt1:"text-transform: capitalize;",
            opt2:"text-transform: uppercase; ",
            opt3:"text-transform: lowercase;",
            opt4:"font-size: capitalize;",
            ans:"text-transform: capitalize;",
    },
    {
        id:"6" ,
        question: "How do you add a comment in a CSS file?",
        opt1:"// this is a comment",
        opt2:"<!-- this is a comment -->",
        opt3:"/* this is a comment */",
        opt4:"# this is a comment",
        ans:"/* this is a comment */",
    },
{
        id:"7" ,
        question: "How do you create a function in JavaScript?",
        opt1:"function:myFunction()",
        opt2:"function myFunction()",
        opt3:"function = myFunction()",
        opt4:"create myFunction()",
        ans:"function myFunction()",   
},
{
        id:"8" ,
        question: "How do you find the number with the highest value of x and y?",
        opt1:"Math.ceil(x, y)",
        opt2:"top(x, y)",
        opt3:"Math.max(x, y)",
        opt4:"Math.high(x, y)",
        ans:"Math.max(x, y)", 
},
{
        id:"9" ,
        question: "Which method is used to select elements by class name in JavaScript?",
        opt1:"document.getElementByClassName()",
        opt2:"document.getElementsByClassName()",
        opt3:"document.getElementsClass()",
        opt4:"document.getClasses()",
        ans:"document.getElementsByClassName()",
        
},
{
        id:"10" ,
        question: "What is the purpose of the addEventListener method in JavaScript",
        opt1:"To send HTTP requests",
        opt2:"To update HTML content",
        opt3:"To remove an HTML element",
        opt4:"To attach an event handler to the specified element",
        ans:"To attach an event handler to the specified element",
},
    ]
    
    export default questions;